[auto_update]
cooldown_days = 7

exclude = "tests/"

[[repos]]
repo = "builtin"
hooks = [
    { id = "trailing-whitespace", args = ["--markdown-linebreak-ext=md"] },
    { id = "mixed-line-ending", args = ["--fix=lf"] },
    { id = "end-of-file-fixer" },
    { id = "detect-private-key" },
    { id = "check-xml" },
    { id = "check-symlinks" },
    { id = "destroyed-symlinks" },
    { id = "check-merge-conflict" },
    { id = "check-json" },
    { id = "check-toml" },
    { id = "check-yaml" },
    { id = "check-shebang-scripts-are-executable" },
    { id = "check-executables-have-shebangs" },
    { id = "check-case-conflict" },
    { id = "fix-byte-order-marker" },
    { id = "check-added-large-files", args = ["--maxkb=1600"] },
]

[[repos]]
repo = "https://github.com/tox-dev/pyproject-fmt"
rev = "v2.21.1"
hooks = [{ id = "pyproject-fmt" }]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.13"
hooks = [
    { id = "ruff-format" },
    { id = "ruff-check", args = ["--fix", "--exit-non-zero-on-fix", "--exclude", "tests/"] },
]

[[repos]]
repo = "https://github.com/osprey-oss/deptry.git"
rev = "0.25.1"
hooks = [{ id = "deptry" }]

[[repos]]
repo = "local"
hooks = [
    { id = "ty", name = "ty static type check", entry = "uv run ty check", language = "system", types = ["python"], pass_filenames = false, args = ["src/"] },
]
